#!/usr/bin/bash
CALEXP=~/tmp/martin.ellison@gmail.com.ics
CANCEL=/tmp/exp.ical
cat >$CANCEL <<DELHEAD
BEGIN:VCALENDAR
METHOD:CANCEL
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:martin.ellison@gmail.com
X-WR-TIMEZONE:Asia/Shanghai
BEGIN:VTIMEZONE
TZID:Asia/Shanghai
X-LIC-LOCATION:Asia/Shanghai
BEGIN:STANDARD
TZOFFSETFROM:+0800
TZOFFSETTO:+0800
TZNAME:CST
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Asia/Hong_Kong
X-LIC-LOCATION:Asia/Hong_Kong
BEGIN:STANDARD
TZOFFSETFROM:+0800
TZOFFSETTO:+0800
TZNAME:HKT
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
DELHEAD
grep UID $CALEXP > /tmp/old-cal
while read -r line
do
    EVENTUID="$line"
    cat >>$CANCEL <<DELEVENT
BEGIN:VEVENT
DTSTAMP:20190626T162729
SEQUENCE:1
STATUS:CANCELLED
UID:$EVENTUID
END:VEVENT
DELEVENT
done < "$CALEXP"
chmod +x $CALEXP
cat >$CANCEL <<DELTAIL
END:VCALENDAR
DELTAIL
